tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#426275",
        "tertiary-fixed-dim": "#ffb4a6",
        "primary-fixed": "#c5e7fd",
        "on-tertiary-fixed": "#3e0501",
        "on-tertiary-container": "#81372a",
        "surface-container-low": "#fff1e9",
        tertiary: "#964739",
        "primary-container": "#a2c4d9",
        "on-surface-variant": "#42484c",
        "on-surface": "#2a1708",
        "outline-variant": "#c2c7cc",
        "secondary-fixed": "#fadebe",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#294b5c",
        "tertiary-container": "#ffaa9b",
        "on-secondary-fixed": "#271905",
        "surface-container": "#ffeadd",
        error: "#ba1a1a",
        "inverse-on-surface": "#ffede3",
        outline: "#72787c",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "secondary-container": "#fadebe",
        "surface-container-highest": "#ffdcc3",
        "on-secondary": "#ffffff",
        "inverse-primary": "#a9cbe0",
        "on-secondary-fixed-variant": "#56442c",
        "on-tertiary-fixed-variant": "#783024",
        "surface-dim": "#f7d3ba",
        background: "#fff8f5",
        secondary: "#6f5b42",
        "on-secondary-container": "#756147",
        "on-primary-container": "#305263",
        "inverse-surface": "#412c1b",
        "on-primary-fixed": "#001e2c",
        "surface-variant": "#ffdcc3",
        surface: "#fff8f5",
        "on-error": "#ffffff",
        "surface-container-high": "#ffe3d0",
        "tertiary-fixed": "#ffdad4",
        "on-background": "#2a1708",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#dcc2a3",
        "surface-bright": "#fff8f5",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#a9cbe0",
        primary: "#426275",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        xl: "64px",
        sm: "12px",
        gutter: "24px",
        lg: "40px",
        "container-max": "1200px",
        base: "8px",
        md: "24px",
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Be Vietnam Pro"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "title-md": ["Plus Jakarta Sans"],
        "body-lg": ["Be Vietnam Pro"],
        "label-md": ["Be Vietnam Pro"],
        "display-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Be Vietnam Pro"],
      },
      fontSize: {
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            fontWeight: "700",
          },
        ],
        "body-md": [
          "16px",
          {
            lineHeight: "24px",
            fontWeight: "400",
          },
        ],
        "headline-lg-mobile": [
          "28px",
          {
            lineHeight: "36px",
            fontWeight: "700",
          },
        ],
        "title-md": [
          "20px",
          {
            lineHeight: "28px",
            fontWeight: "700",
          },
        ],
        "body-lg": [
          "18px",
          {
            lineHeight: "28px",
            fontWeight: "400",
          },
        ],
        "label-md": [
          "14px",
          {
            lineHeight: "20px",
            letterSpacing: "0.01em",
            fontWeight: "600",
          },
        ],
        "display-lg": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.02em",
            fontWeight: "800",
          },
        ],
        "label-sm": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.03em",
            fontWeight: "700",
          },
        ],
      },
    },
  },
};
